add_subdirectory(iso9660)
add_subdirectory(mpq)
add_subdirectory(tbl)
add_subdirectory(dc6)
add_subdirectory(dt1)
add_subdirectory(ds1)
add_subdirectory(cof)
add_subdirectory(dcc)
add_subdirectory(devctl)
add_subdirectory(screenshot)
add_subdirectory(palette)
add_subdirectory(font)
add_subdirectory(d2s)
add_subdirectory(userdir)
add_subdirectory(txt)
add_subdirectory(compcode)
add_subdirectory(rules)
add_subdirectory(drlg)
add_subdirectory(game)
